// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOwgnIjmRMG1jA8iC4l-6rbdbfu2SEEI',
    appId: '1:719628557144:web:ac7643e02bc40c245f632d',
    messagingSenderId: '719628557144',
    projectId: 'gdsc-demo-f30e7',
    authDomain: 'gdsc-demo-f30e7.firebaseapp.com',
    storageBucket: 'gdsc-demo-f30e7.appspot.com',
    measurementId: 'G-X1JMZF4WF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfIPjih4iaNggK8qpl4l_xkK3twRaR98',
    appId: '1:719628557144:android:830ce7e32dd198025f632d',
    messagingSenderId: '719628557144',
    projectId: 'gdsc-demo-f30e7',
    storageBucket: 'gdsc-demo-f30e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq7dxG5WGdBUT72x4FXlYlQUWEp9QXt0Q',
    appId: '1:719628557144:ios:880bcc3fc1d7cf295f632d',
    messagingSenderId: '719628557144',
    projectId: 'gdsc-demo-f30e7',
    storageBucket: 'gdsc-demo-f30e7.appspot.com',
    iosBundleId: 'dev.julianhartl.gdscDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq7dxG5WGdBUT72x4FXlYlQUWEp9QXt0Q',
    appId: '1:719628557144:ios:1bf11152b1ee71325f632d',
    messagingSenderId: '719628557144',
    projectId: 'gdsc-demo-f30e7',
    storageBucket: 'gdsc-demo-f30e7.appspot.com',
    iosBundleId: 'dev.julianhartl.gdscDemo.RunnerTests',
  );
}
